name: ArkMMO
version: '${project.version}'
main: fr.skytryx.arkmmo.ArkMMO
api-version: '1.20'
commands:
  claim:
    description: Claim a chunk
  unclaim:
    description: Unclaim a chunk
  adminclaim:
    description: Manage claims
    permission: arkmmo.adminclaim
  guildcreate:
    description: Create a guild
  guildinvite:
    description: Invite someone to your guild
  guildjoin:
    description: Join a guild you were invited to
  guildmsg:
    description: send a message in your guild chat!
  guildinfo:
    description: get info about a guild
  guildleave:
    description: leave a guild
  guildkick:
    description: Kick a player from your guild