name: ArkMMO
version: '${project.version}'
main: fr.skytryx.arkmmo.ArkMMO
api-version: '1.20'
commands:
  claim:
    description: Claim a chunk
  unclaim:
    description: Unclaim a chunk
  adminclaim:
    description: Manage claims
    permission: arkmmo.adminclaim
  guildcreate:
    description: Create a guild
  guildinvite:
    description: Invite someone to your guild
  guildjoin:
    description: Join a guild you were invited to
  guildmsg:
    description: send a message in your guild chat!
  guildinfo:
    description: get info about a guild
  guildleave:
    description: leave a guild
  guildkick:
    description: Kick a player from your guild
  guilddisband:
    description: Disband your own guild
  guildpromote:
    description: Promote someone in your guild
  guilddemote:
    description: Demote someone in your guild
  giveitem:
    description: To give yourself special items
    permission: arkmmo.giveitem
  seeclaim:
    description: See claims around you
  bypassclaim:
    description: Grants you full perms over claims
    permission: arkmmo.bypassclaim
  gemsincruster:
    description: opens a gui to incrust a gem
    permission: arkmmo.gemsincruster
  lobbyregion:
    description: Create a region that is only editable by op players
    permission: arkmmo.lobbyregion
  addgold:
    description: Add gold to a player
    permission: arkmmo.addgold
  removegold:
    description: remove gold to a player
    permission: arkmmo.removegold
  setgold:
    description: Set gold to a player
    permission: arkmmo.setgold
  spawnmob:
    description: juan.
    permission: arkmmo.spawnmob
  mobregion:
    description: Create region of mob spawn
    permission: arkmmo.mobregion